### ISSUE TITLE
Error when using script 

### ISSUE THREAD

**Issue by ccrossman28** [Claytonjmartin/LandisContactCenterScripts#1]
I was getting an error using the script when I tried to use just the call forwarding option instead of the menu option.  After some tinkering with the script I found the -EnableTranscription $false at the end of the statements was causing the error because the -EnableTranscription setting is actually not a boolean statement.  I removed those from the end of the script and everything worked fine after that. Just wanted to let you know! 

And thanks for the script. Made my life so much easier!

**Comment by claytonmartin** [comment]
Thanks for letting me know. I have updated the script.

**Comment by Claytonjmartin** [comment]
Thanks for letting me know. I have updated the script.
